baseurl = "https://riselocal.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-tempo"
disqusShortname = "risedev"

[taxonomies]
tag = "tags"
topic = "topics"
2016 = "2016"
2017 = "2017"
2018 = "2018"

[params.logo]
logo = "riselocal-logo.png"
alt = "test test test"

[params.social]
facebook = "https://www.facebook.com/status26inc/"

[params.signup]
enable = true
hook = "Are You Crazy?"
detail = "....then don't miss this opportunity to sign up for our FREE marketing course."

# PAGE CONFIG

# Promo Section
[params.promo]
enable = true
hook = "Fire Your Your Webmaster"
detail = "Start getting better marketing results at lower costs."
ctaButton = "Tell me more!"
ctaURL = "tour"

[params.promo.signup]
enable = true
hook = "Turn your local business into a Lead Genertion Machine!"
detail = "Signup for Our Free Online Marketing Course for Business Owners"

# Press section
[params.press]
enable = true

# Why section
[params.why]
enable = false

# Video section
[params.video]
enable = false

# Faq section
[params.faq]
enable = false
