podium:
  image: nginx:1.11.3-alpine
  ports:
    - 80:80
  volumes:
    - ./public:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx.conf
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
